version: "3.9"

x-next-env: &next-env
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
  NODE_ENV: production
  NEXT_PUBLIC_ENABLE_DEVTOOLS: "true"
  NEXT_PUBLIC_DEPLOYMENT_ENV: staging
  PORT: 3001

services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_ENABLE_DEVTOOLS: "true"
        NEXT_PUBLIC_DEPLOYMENT_ENV: staging
    image: eventzflow-panel-web-staging:latest
    environment:
      <<: *next-env
    ports:
      - "3001"
    healthcheck:
      test:
        [
          "CMD",
          "bun",
          "-e",
          "fetch('http://localhost:3001/api/health').then((r) => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - coolify
    # labels:
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.regex=^(http|https)://www\.(.+)
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.replacement=${1}://${2}
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.permanent=true

networks:
  coolify:
    external: true
