version: "3.9"

x-next-env: &next-env
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
  NODE_ENV: production
  NEXT_PUBLIC_DEPLOYMENT_ENV: production
  PORT: 3001

services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_DEPLOYMENT_ENV: production
    image: eventzflow-panel-web:latest
    environment:
      <<: *next-env
    ports:
      - "3001"
    networks:
      - coolify
    # labels:
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.regex=^(http|https)://www\.(.+)
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.replacement=${1}://${2}
    #   - traefik.http.middlewares.eventzflow-redirect-www-to-non-www.redirectregex.permanent=true

networks:
  coolify:
    external: true
